[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "script-src 'self' 'unsafe-eval' 'unsafe-inline' https://cdnjs.cloudflare.com; connect-src 'self' https://*.supabase.co https://fonts.googleapis.com https://fonts.gstatic.com;"
